export const StandaloneOSX = 'StandaloneOSXUniversal';
export const StandaloneOSXUniversal = 'StandaloneOSXUniversal'; // @UnityVersion remove when 5.x support is dropped
export const StandaloneOSXIntel = 'StandaloneOSXIntel'; // @UnityVersion remove when 5.x support is dropped
export const StandaloneWindows = 'StandaloneWindows';
export const iOS = 'iOS';
export const Android = 'Android';
export const StandaloneLinux = 'StandaloneLinux';
export const StandaloneWindows64 = 'StandaloneWindows64';
export const WebGL = 'WebGL';
export const WSAPlayer = 'WSAPlayer';
export const StandaloneLinux64 = 'StandaloneLinux64';
export const StandaloneLinuxUniversal = 'StandaloneLinuxUniversal';
export const StandaloneOSXIntel64 = 'StandaloneOSXIntel64'; // @UnityVersion remove when 5.x support is dropped
export const Tizen = 'Tizen';
export const PSP2 = 'PSP2';
export const PS4 = 'PS4';
export const XboxOne = 'XboxOne';
export const SamsungTV = 'SamsungTV'; // @UnityVersion remove when 5.x support is dropped
export const N3DS = 'N3DS';
export const WiiU = 'WiiU';
export const tvOS = 'tvOS';
export const Switch = 'Switch';
